source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TextImageButton_Example', :exclusive => true do
  pod "TextImageButton", :path => "../"
end

target 'TextImageButton_Tests', :exclusive => true do
  pod "TextImageButton", :path => "../"
  pod "Quick"
  pod "Nimble"
end
